import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:macos_ui/macos_ui.dart';

import '../../../../config/theme/colors/theme_colors.dart';
import '../../../../config/theme/theme.dart';

class ContactHighlightRow extends StatefulWidget {
  const ContactHighlightRow({
    super.key,
    required this.displayName,
    required this.shortName,
    this.summaryLine,
    this.useHeroTitleStyle = false,
    this.contentPadding,
    this.contentLeftGutter,
    this.onTap,
  });

  final String displayName;
  final String shortName;
  final String? summaryLine;
  final bool useHeroTitleStyle;
  final EdgeInsets? contentPadding;
  final double? contentLeftGutter;
  final VoidCallback? onTap;

  @override
  State<ContactHighlightRow> createState() => _ContactHighlightRowState();
}

class _ContactHighlightRowState extends State<ContactHighlightRow> {
  bool _isHovered = false;

  @override
  Widget build(BuildContext context) {
    return Consumer(
      builder: (context, ref, child) {
        final theme = MacosTheme.of(context);
        ref.watch(themeColorsProvider);
        final colors = ref.read(themeColorsProvider.notifier);

        final titleStyle = widget.useHeroTitleStyle
            ? AppTheme.cassetteHeroTitleStyle(context)
            : theme.typography.body.copyWith(color: colors.content.textPrimary);

        final content = Padding(
          padding:
              widget.contentPadding ??
              const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
          child: Row(
            children: [
              if (widget.contentLeftGutter != null)
                SizedBox(width: widget.contentLeftGutter),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text(
                      widget.displayName,
                      style: titleStyle,
                      overflow: TextOverflow.ellipsis,
                    ),
                    if (widget.shortName != widget.displayName)
                      Text(
                        widget.shortName,
                        style: theme.typography.caption2.copyWith(
                          color: colors.content.textSecondary,
                        ),
                        overflow: TextOverflow.ellipsis,
                      ),
                    if (widget.summaryLine != null) ...[
                      const SizedBox(height: 6),
                      Text(
                        widget.summaryLine!,
                        style: theme.typography.caption1.copyWith(
                          color: colors.content.textSecondary,
                        ),
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                      ),
                    ],
                  ],
                ),
              ),
            ],
          ),
        );

        final decorated = DecoratedBox(
          decoration: BoxDecoration(
            color: _isHovered
                ? colors.accents.primary.withValues(alpha: 0.15)
                : Colors.transparent,
            borderRadius: BorderRadius.circular(10),
          ),
          child: content,
        );

        final onTapCallback = widget.onTap;
        if (onTapCallback == null) {
          return MouseRegion(
            onEnter: (_) => setState(() => _isHovered = true),
            onExit: (_) => setState(() => _isHovered = false),
            child: decorated,
          );
        }

        return MouseRegion(
          cursor: SystemMouseCursors.click,
          onEnter: (_) => setState(() => _isHovered = true),
          onExit: (_) => setState(() => _isHovered = false),
          child: GestureDetector(
            behavior: HitTestBehavior.opaque,
            onTap: onTapCallback,
            child: decorated,
          ),
        );
      },
    );
  }
}

class ContactHeroHeaderHighlight extends ConsumerWidget {
  const ContactHeroHeaderHighlight({
    super.key,
    required this.displayName,
    required this.autoGeneratedName,
    required this.summaryLine,
    this.onEdit,
    required this.onChange,
  });

  /// The effective display name (user override if set, else auto-generated).
  final String displayName;

  /// The algorithm-generated name from AddressBook import.
  /// Shown as identity anchor subtitle when different from displayName.
  final String autoGeneratedName;

  final String summaryLine;

  /// Callback for "edit" link to customize the display name.
  /// If null, the edit link is not shown.
  final VoidCallback? onEdit;

  final VoidCallback onChange;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = MacosTheme.of(context);
    // Watch the brightness state to trigger rebuilds
    ref.watch(themeColorsProvider);
    final colors = ref.read(themeColorsProvider.notifier);

    final tint = colors.accents.primary.withValues(alpha: 0.10);
    final accent = colors.accents.primary.withValues(alpha: 0.75);
    final linkColor = colors.accents.primary;
    final linkBaseStyle = theme.typography.body.copyWith(color: linkColor);

    return ConstrainedBox(
      constraints: const BoxConstraints(minHeight: 64),
      child: DecoratedBox(
        decoration: BoxDecoration(
          color: tint,
          borderRadius: BorderRadius.circular(10),
        ),
        child: Row(
          children: [
            DecoratedBox(
              decoration: BoxDecoration(
                color: accent,
                borderRadius: const BorderRadius.only(
                  topLeft: Radius.circular(10),
                  bottomLeft: Radius.circular(10),
                ),
              ),
              child: const SizedBox(width: 4),
            ),
            Expanded(
              child: Padding(
                padding: const EdgeInsets.symmetric(
                  horizontal: 16,
                  vertical: 8,
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Row(
                      children: [
                        Expanded(
                          child: Text(
                            displayName,
                            style: AppTheme.cassetteHeroTitleStyle(context),
                            overflow: TextOverflow.ellipsis,
                          ),
                        ),
                        const SizedBox(width: 10),
                        if (onEdit != null) ...[
                          _HoverLink(
                            label: 'edit',
                            baseStyle: linkBaseStyle,
                            onTap: onEdit!,
                          ),
                          const SizedBox(width: 8),
                        ],
                        _HoverLink(
                          label: 'change…',
                          baseStyle: linkBaseStyle,
                          onTap: onChange,
                        ),
                      ],
                    ),
                    if (autoGeneratedName != displayName)
                      Text(
                        autoGeneratedName,
                        style: theme.typography.caption2.copyWith(
                          color: colors.content.textSecondary,
                        ),
                        overflow: TextOverflow.ellipsis,
                      ),
                    const SizedBox(height: 4),
                    Text(
                      summaryLine,
                      style: theme.typography.caption1.copyWith(
                        color: colors.content.textSecondary,
                      ),
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _HoverLink extends StatefulWidget {
  const _HoverLink({
    required this.label,
    required this.baseStyle,
    required this.onTap,
  });

  final String label;
  final TextStyle baseStyle;
  final VoidCallback onTap;

  @override
  State<_HoverLink> createState() => _HoverLinkState();
}

class _HoverLinkState extends State<_HoverLink> {
  bool _isHovering = false;
  bool _isPressed = false;

  @override
  Widget build(BuildContext context) {
    final baseColor = widget.baseStyle.color;
    final hoverColor = baseColor?.withValues(alpha: 0.85);
    final active = _isHovering || _isPressed;
    final style = widget.baseStyle.copyWith(
      color: active ? hoverColor : baseColor,
      decoration: active ? TextDecoration.underline : TextDecoration.none,
    );

    return MouseRegion(
      cursor: SystemMouseCursors.click,
      onEnter: (_) {
        if (_isHovering) {
          return;
        }
        setState(() {
          _isHovering = true;
        });
      },
      onExit: (_) {
        if (!_isHovering) {
          return;
        }
        setState(() {
          _isHovering = false;
        });
      },
      child: Listener(
        onPointerDown: (_) {
          setState(() {
            _isPressed = true;
          });
        },
        onPointerUp: (_) {
          setState(() {
            _isPressed = false;
          });
        },
        onPointerCancel: (_) {
          setState(() {
            _isPressed = false;
          });
        },
        child: GestureDetector(
          behavior: HitTestBehavior.opaque,
          onTap: widget.onTap,
          child: Padding(
            padding: const EdgeInsets.symmetric(vertical: 2, horizontal: 2),
            child: Text(widget.label, style: style),
          ),
        ),
      ),
    );
  }
}
