import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

import '../../../../config/theme/colors/theme_colors.dart';
import '../../../../config/theme/theme_typography.dart';

class ContactHighlightRow extends StatefulWidget {
  const ContactHighlightRow({
    super.key,
    required this.displayName,
    required this.shortName,
    this.summaryLine,
    this.useHeroTitleStyle = false,
    this.contentPadding,
    this.contentLeftGutter,
    this.onTap,
  });

  final String displayName;
  final String shortName;
  final String? summaryLine;
  final bool useHeroTitleStyle;
  final EdgeInsets? contentPadding;
  final double? contentLeftGutter;
  final VoidCallback? onTap;

  @override
  State<ContactHighlightRow> createState() => _ContactHighlightRowState();
}

class _ContactHighlightRowState extends State<ContactHighlightRow> {
  bool _isHovered = false;

  @override
  Widget build(BuildContext context) {
    return Consumer(
      builder: (context, ref, child) {
        ref.watch(themeColorsProvider);
        final colors = ref.read(themeColorsProvider.notifier);
        final typography = ref.watch(themeTypographyProvider);

        final titleStyle = widget.useHeroTitleStyle
            ? typography.heroTitle
            : typography.body;

        final content = Padding(
          padding:
              widget.contentPadding ??
              const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
          child: Row(
            children: [
              if (widget.contentLeftGutter != null)
                SizedBox(width: widget.contentLeftGutter),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text(
                      widget.displayName,
                      style: titleStyle,
                      overflow: TextOverflow.ellipsis,
                    ),
                    if (widget.shortName != widget.displayName)
                      Text(
                        widget.shortName,
                        style: typography.heroSubtitle,
                        overflow: TextOverflow.ellipsis,
                      ),
                    if (widget.summaryLine != null) ...[
                      const SizedBox(height: 6),
                      Text(
                        widget.summaryLine!,
                        style: typography.caption,
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                      ),
                    ],
                  ],
                ),
              ),
            ],
          ),
        );

        final decorated = DecoratedBox(
          decoration: BoxDecoration(
            color: _isHovered
                ? colors.accents.primary.withValues(alpha: 0.15)
                : Colors.transparent,
            borderRadius: BorderRadius.circular(10),
          ),
          child: content,
        );

        final onTapCallback = widget.onTap;
        if (onTapCallback == null) {
          return MouseRegion(
            onEnter: (_) => setState(() => _isHovered = true),
            onExit: (_) => setState(() => _isHovered = false),
            child: decorated,
          );
        }

        return MouseRegion(
          cursor: SystemMouseCursors.click,
          onEnter: (_) => setState(() => _isHovered = true),
          onExit: (_) => setState(() => _isHovered = false),
          child: GestureDetector(
            behavior: HitTestBehavior.opaque,
            onTap: onTapCallback,
            child: decorated,
          ),
        );
      },
    );
  }
}

class ContactHeroHeaderHighlight extends ConsumerWidget {
  const ContactHeroHeaderHighlight({
    super.key,
    required this.displayName,
    required this.autoGeneratedName,
    required this.summaryLine,
    this.onEdit,
  });

  /// The effective display name (user override if set, else auto-generated).
  final String displayName;

  /// The algorithm-generated name from AddressBook import.
  /// Shown as identity anchor subtitle when different from displayName.
  final String autoGeneratedName;

  final String summaryLine;

  /// Callback for "edit" link to customize the display name.
  /// If null, the name is not editable.
  final VoidCallback? onEdit;

  /// Whether the display name is user-customized (different from auto-generated).
  bool get _isUserOverridden => displayName != autoGeneratedName;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Watch the brightness state to trigger rebuilds
    ref.watch(themeColorsProvider);
    final colors = ref.read(themeColorsProvider.notifier);
    final typography = ref.watch(themeTypographyProvider);

    final tint = colors.accents.primary.withValues(alpha: 0.10);
    final accent = colors.accents.primary.withValues(alpha: 0.75);

    return ConstrainedBox(
      constraints: const BoxConstraints(minHeight: 64),
      child: DecoratedBox(
        decoration: BoxDecoration(
          color: tint,
          borderRadius: BorderRadius.circular(10),
        ),
        child: Row(
          children: [
            DecoratedBox(
              decoration: BoxDecoration(
                color: accent,
                borderRadius: const BorderRadius.only(
                  topLeft: Radius.circular(10),
                  bottomLeft: Radius.circular(10),
                ),
              ),
              child: const SizedBox(width: 4),
            ),
            Expanded(
              child: Padding(
                padding: const EdgeInsets.symmetric(
                  horizontal: 16,
                  vertical: 10,
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    // Primary: Name + pencil as single interactive target
                    if (onEdit != null)
                      _NameEditTarget(
                        displayName: displayName,
                        isUserOverridden: _isUserOverridden,
                        onEdit: onEdit!,
                        typography: typography,
                        colors: colors,
                      )
                    else
                      Text(
                        displayName,
                        style: typography.heroTitle,
                        overflow: TextOverflow.ellipsis,
                      ),

                    // Vertical separation from title
                    const SizedBox(height: 10),

                    // Secondary: Identity anchor (only shown when overridden)
                    if (_isUserOverridden) ...[
                      Text(
                        autoGeneratedName,
                        style: typography.heroSubtitle,
                        overflow: TextOverflow.ellipsis,
                      ),
                      const SizedBox(height: 4),
                    ],

                    // Metadata: summary line
                    Text(
                      summaryLine,
                      style: typography.heroMeta,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

/// Interactive target combining name text and pencil icon.
///
/// Per the interaction spec:
/// - The NAME is the control, pencil is secondary hint
/// - Single hover target for name + icon
/// - Hover: name changes to accent, pencil increases contrast
/// - Focus: mirrors hover state
/// - Click/Enter/Space opens edit dialog
/// - Tooltip after 700ms (assistive only)
class _NameEditTarget extends StatefulWidget {
  const _NameEditTarget({
    required this.displayName,
    required this.isUserOverridden,
    required this.onEdit,
    required this.typography,
    required this.colors,
  });

  final String displayName;
  final bool isUserOverridden;
  final VoidCallback onEdit;
  final ThemeTypography typography;
  final ThemeColors colors;

  @override
  State<_NameEditTarget> createState() => _NameEditTargetState();
}

class _NameEditTargetState extends State<_NameEditTarget> {
  bool _isHovered = false;
  bool _isFocused = false;

  bool get _isActive => _isHovered || _isFocused;

  @override
  Widget build(BuildContext context) {
    final hints = widget.colors.interactiveHints;

    // Pencil icon contrast: very subtle at rest, more visible on hover
    // If user-overridden, slightly more visible at rest to hint customization
    final pencilRestAlpha = widget.isUserOverridden
        ? hints.iconRestAlphaOverridden
        : hints.iconRestAlpha;
    final pencilColor = widget.colors.content.textPrimary.withValues(
      alpha: _isActive ? hints.iconActiveAlpha : pencilRestAlpha,
    );

    // Name color: stays primary always (no color change on hover)
    final nameColor = widget.colors.content.textPrimary;

    // Subtle background lift on hover
    final bgColor = _isActive ? hints.backgroundLift : Colors.transparent;

    return Semantics(
      button: true,
      label: 'Edit display name: ${widget.displayName}',
      child: Focus(
        onFocusChange: (focused) => setState(() => _isFocused = focused),
        onKeyEvent: (node, event) {
          // Enter or Space activates
          if (event is KeyDownEvent &&
              (event.logicalKey == LogicalKeyboardKey.enter ||
                  event.logicalKey == LogicalKeyboardKey.space)) {
            widget.onEdit();
            return KeyEventResult.handled;
          }
          return KeyEventResult.ignored;
        },
        child: Tooltip(
          message: 'Click to edit display name',
          waitDuration: const Duration(milliseconds: 700),
          preferBelow: false,
          child: MouseRegion(
            cursor: SystemMouseCursors.click,
            onEnter: (_) => setState(() => _isHovered = true),
            onExit: (_) => setState(() => _isHovered = false),
            child: GestureDetector(
              behavior: HitTestBehavior.opaque,
              onTap: widget.onEdit,
              child: AnimatedContainer(
                duration: const Duration(milliseconds: 120),
                decoration: BoxDecoration(
                  color: bgColor,
                  borderRadius: BorderRadius.circular(hints.cornerRadius),
                ),
                // Asymmetric padding: more vertical for breathing room
                padding: EdgeInsets.symmetric(
                  horizontal: hints.paddingHorizontal,
                  vertical: hints.paddingVertical,
                ),
                // Negative margin to offset horizontal padding
                transform:
                    Matrix4.translationValues(-hints.paddingHorizontal, 0, 0),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    Flexible(
                      child: Text(
                        widget.displayName,
                        style: widget.typography.heroTitle.copyWith(
                          color: nameColor,
                        ),
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                    const SizedBox(width: 6),
                    Icon(
                      CupertinoIcons.pencil,
                      size: 16,
                      color: pencilColor,
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
